name: EshopOnVue.js Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore EshopOnVue.js
    - name: Build
      run: dotnet build EshopOnVue.js --no-restore
    - name: Test
      run: dotnet test EshopOnVue.js --no-build --verbosity normal
